const English = {
  success: "success",
  verifyUserAndPassword: "verify username and password",
  username: "username",
  password: "password",
  access: "access",
  auth: "authentication",
  cashier: "cashier",
  connect: "connect",
  connecter: "Login ",
  reset: "reset",
  freeTable: "free table",
  busytables: "busy table",
  newTable: "new table",
  nbrCouverts: "number of person",
  validate: "validate",
  backToTable: "back to tables",
  couverts: "person",
  artice: "article",
  price: "price",
  surplace: "Direct ",
  tiroir: "cash register",
  cancel: "cancel",
  added: "added",
  disconnect: "disconnect",
  closureHistory: "closure history",
  selectDate: "select a date",
  print: "print",
  latestClosure: "latest closure",
  TotalInit: "initial cashier total",
  close: "close",
  ofCashier: "of cash register",
  confirm: "Confirm",
  cashierr: "Cash Register",
};
export default English;
