const Francais = {
  success: "success",
  verifyUserAndPassword: "verifier utilisateur et mot de passe",
  username: "utilisateur",
  password: "mot de passe",
  access: "acceder",
  auth: "authentification",
  cashier: "caisse",
  connect: "Connexion",
  connecter: "Se connecter",
  reset: "reset",
  freeTable: "table libre",
  busytables: "table en cours",
  newTable: "Nouvelle Table",
  nbrCouverts: "nombre de couverts",
  validate: "valider",
  backToTable: "retour Au Tables",
  couverts: "couverts",
  artice: "Nom",
  price: "prix",
  surplace: "sur place ",
  tiroir: "Tiroir",
  cancel: "Annuler",
  aded: "ajouter",
  disconnect: "déconnexion",
  closureHistory: "historique de clôtures",
  selectDate: "séléctionner une date",
  print: "imprimer",
  latestClosure: "Derniere Clôture",
  TotalInit: "total de caisse initial",
  close: "clôturer",
  ofCashier: "de caisse",
  cashierr: "Caisse",
  confirm: "OK",
};
export default Francais;
